QuanLyTaiSan_UserManagement/Controllers/Account_App_NewController.cs
using Microsoft.AspNet.Identity;
using QuanLyTaiSan_UserManagement.Common;
using QuanLyTaiSan_UserManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace QuanLyTaiSan_UserManagement.Controllers
{
    public class Account_App_NewController : Controller
    {
        // GET: Account_App_New
        public ActionResult Login_New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login_New(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDao();
                var result = dao.Login(model.UserName,model.Password/*model.Password*/);
                if (1 == 1)
                {
                    var user = dao.GetById(model.UserName);
                    var userSession = new UserLoginSec();
                    userSession.UserName = user.UserName;
                    userSession.UserID = user.Id;
                    userSession.GroupID = user.GroupID; 
                    Session.Add(CommonConstants.USER_SESSION, userSession);
                    // List quyền của ng dùng
                    List<string> privilegeLevelsNew = dao.GetListCredential(user.UserName.Trim());
                    Session.Add(CommonConstants.SESSION_CREDENTIALS, privilegeLevelsNew);
                    return RedirectToAction("Index", "Home");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại.");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài khoản đang bị khoá.");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Mật khẩu không đúng.");
                }
                else if (result == -3)
                {
                    ModelState.AddModelError("", "Tài khoản của bạn không có quyền truy cập ");
                }
                else
                {
                    ModelState.AddModelError("", "đăng nhập không đúng.");
                }
            }
            return View(model);
        }

     
    }
}

QuanLyTaiSan_UserManagement/Views/Account_App_New/Login_New.cshtml
@model QuanLyTaiSan_UserManagement.Models.LoginModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Đăng nhập - Quản Lý Tài Sản</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="/Content/Loginform/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/Content/Loginform/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/Content/Loginform/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/Content/Loginform/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/Content/Loginform/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/Content/Loginform/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/Content/Loginform/css/util.css">
    <link rel="stylesheet" type="text/css" href="/Content/Loginform/css/main.css">
    <!--===============================================================================================-->
</head>
<body>

    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-pic js-tilt" data-tilt>
                    <img src="~/Content/Loginform/images/logoTDMU1.jpg" alt="IMG" style="height:316px; margin-bottom:141px">
                </div>

                @using (Html.BeginForm("Login_New", "Account_App_New", FormMethod.Post, new { @class = "form-horizontal form-signin", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    <span class="login100-form-title">
                        Login Member
                    </span>

                    <div class="wrap-input100 validate-input">
                        <input class="input100" type="text" name="UserName" placeholder="Username" required>
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input">
                        <input class="input100" type="password" name="Password" placeholder="Password" required>
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-lock" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn">
                            Login
                        </button>
                    </div>

                }
            </div>
        </div>
    </div>




    <!--===============================================================================================-->
    <script src="/Content/Loginform/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="/Content/Loginform/vendor/bootstrap/js/popper.js"></script>
    <script src="/Content/Loginform/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="/Content/Loginform/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="/Content/Loginform/vendor/tilt/tilt.jquery.min.js"></script>
    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
    <!--===============================================================================================-->
    <script src="/Content/Loginform/js/main.js"></script>

</body>
</html>